# Generated by Django 4.1.7 on 2024-03-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_select', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name='coursesection',
            constraint=models.UniqueConstraint(fields=('course', 'section'), name='course_section'),
        ),
        migrations.AddConstraint(
            model_name='professorrating',
            constraint=models.UniqueConstraint(fields=('student', 'professor', 'course'), name='student_rating'),
        ),
    ]
