# Generated by Django 4.1.7 on 2024-03-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_select', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionschedule',
            name='period',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sectionschedule',
            name='day_schedule',
            field=models.CharField(choices=[('Monday - Thursday', 'Monday - Thursday'), ('Tuesday - Friday', 'Tuesday - Friday'), ('Wednesday', ' Wednesday'), ('Saturday', 'Saturday')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sectionschedule',
            name='time_schedule',
            field=models.CharField(choices=[('8:00 - 9:30', '8:00 - 9:30'), ('9:30 - 11:00', '9:30 - 11:00'), ('11:00 - 12:30', '11:00 - 12:30'), ('12:30 - 14:00', '12:30 - 14:00'), ('14:00 - 15:30', '14:00 - 15:30'), ('15:30 - 17:00', '15:30 - 17:00'), ('17:00 - 18:30', '17:00 - 18:30'), ('18:30 - 20:00', '18:30 - 20:00'), ('9:00 - 12:00', '9:00 - 12:00'), ('12:00 - 15:00', '12:00 - 15:00'), ('15:00 - 18:00', '15:00 - 18:00'), ('18:00 - 21:00', '18:00 - 21:00')], max_length=20),
        ),
    ]
