# Generated by Django 4.1.7 on 2024-03-10 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_alter_department_email_alter_student_email'),
        ('professor_select', '0002_alter_course_course_code_alter_professor_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor_select.course')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor_select.professor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='landing_page.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='professorfavorite',
            constraint=models.UniqueConstraint(fields=('student', 'professor', 'course'), name='student_favorite'),
        ),
    ]
