# Generated by Django 4.1.7 on 2024-03-24 23:53

from django.db import migrations, models
import django.db.models.deletion
import professor_select.models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0004_alter_department_department_name_and_more'),
        ('professor_select', '0002_sectionschedule_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesection',
            name='department',
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(default=professor_select.models.get_department, on_delete=django.db.models.deletion.CASCADE, related_name='department_classes', to='landing_page.department'),
        ),
    ]
