# Generated by Django 4.1.7 on 2024-03-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_select', '0003_remove_coursesection_department_course_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesection',
            name='slots',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='venue',
            field=models.CharField(default='TBA', max_length=255),
        ),
    ]
