# Generated by Django 4.1.7 on 2024-03-11 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professor_select', '0003_professorfavorite_professorfavorite_student_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesection',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_sections', to='professor_select.course'),
        ),
    ]
