# Generated by Django 4.1.7 on 2024-04-12 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0004_alter_department_department_name_and_more'),
        ('professor_select', '0004_alter_coursesection_slots_alter_coursesection_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesection',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='professor_select.course'),
        ),
        migrations.AlterField(
            model_name='coursestudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='landing_page.student'),
        ),
    ]
