# Generated by Django 4.1.7 on 2024-04-13 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0004_alter_department_department_name_and_more'),
        ('professor_select', '0005_alter_coursesection_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professorrating',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='professor_select.professor'),
        ),
        migrations.AlterField(
            model_name='professorrating',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_reviews', to='landing_page.student'),
        ),
    ]
