# Generated by Django 4.1.7 on 2024-03-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_select', '0005_alter_professorrating_approachability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionschedule',
            name='day_schedule',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday')], max_length=20),
        ),
    ]
