# Generated by Django 4.1.7 on 2024-03-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_select', '0006_alter_sectionschedule_day_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionschedule',
            name='day_schedule',
            field=models.CharField(max_length=20),
        ),
    ]
