# Generated by Django 4.1.7 on 2024-04-16 23:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professor_select', '0006_alter_professorrating_professor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professorrating',
            name='rating_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='professorfavorite',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='professor_select.course'),
        ),
    ]
