# Generated by Django 4.1.7 on 2024-04-12 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landing_page', '0004_alter_department_department_name_and_more'),
        ('professor_select', '0005_alter_coursesection_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor_select.coursesection')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='landing_page.student')),
            ],
        ),
        migrations.CreateModel(
            name='RequiredCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor_select.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_courses', to='landing_page.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='studentschedule',
            constraint=models.UniqueConstraint(fields=('course_section', 'student'), name='student_schedule'),
        ),
        migrations.AddConstraint(
            model_name='requiredcourse',
            constraint=models.UniqueConstraint(fields=('course', 'student'), name='required_course'),
        ),
    ]
