# Generated by Django 4.1.7 on 2024-04-12 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professor_select', '0005_alter_coursesection_course_and_more'),
        ('landing_page', '0004_alter_department_department_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upvotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='professor_select.professorrating')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='upvotes',
            constraint=models.UniqueConstraint(fields=('student', 'rating'), name='student_upvote'),
        ),
    ]
