# Generated by Django 4.1.7 on 2024-04-16 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0004_alter_department_department_name_and_more'),
        ('rate_a_professor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvotes',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_upvotes', to='landing_page.student'),
        ),
    ]
