# Generated by Django 4.1.7 on 2024-03-23 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_alter_department_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='department_ID',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_ID',
            field=models.IntegerField(default=200000),
        ),
    ]
